package modelo.SimulacroExamen2;

import java.util.concurrent.CompletionException;

public class GestionaDeportista {

	public static void main(String[] args)  {
		
	throw new CompeticionExcepcion("Mi excepcion");

		try {
			g1.getMessage();
		} catch (CompeticionExcepcion e) {
			System.out.println(e.getMessage());
		}
		
	}

}
